### ISSUE TITLE
--ansible options are expected for tests that do not use this plugin

### ISSUE THREAD

**Issue by dotIN** [jlaska/pytest-ansible#2]
I installed this plugin to try ansible and later when I created a different test file which was not using this plugin , I was unable to execute pytest. Even executing py.test gives same error 

$ py.test
ERROR: Missing required parameter --ansible-host-pattern

**Comment by jlaska** [comment]
This is expected.  When using the plugin `pytest-ansible`, just like the `ansible` command, certain parameters are required.  You must supply an inventory file, and a host-pattern.  Please consult the `--help` for guidance.

```
pytest-ansible:
  --ansible-inventory=ANSIBLE_INVENTORY
                        ansible inventory file URI (default:
                        /etc/ansible/hosts)
  --ansible-host-pattern=ANSIBLE_HOST_PATTERN
                        ansible host pattern (default: None)
  --ansible-connection=ANSIBLE_CONNECTION
                        connection type to use (default: smart)
  --ansible-user=ANSIBLE_USER
                        connect as this user (default: jlaska)
  --ansible-sudo        run operations with sudo [nopasswd] (default: False)
                        (deprecated, use become)
  --ansible-sudo-user=ANSIBLE_SUDO_USER
                        desired sudo user (default: root) (deprecated, use
                        become)
  --ansible-become      run operations with become, nopasswd implied (default:
                        False)
  --ansible-become-method=ANSIBLE_BECOME_METHOD
                        privilege escalation method to use (default: sudo),
                        valid choices: [ sudo | su | pbrun | pfexec | runas ]
  --ansible-become-user=ANSIBLE_BECOME_USER
                        run operations as this user (default: root)
```

**Comment by jlaska** [comment]
I've reopened this issue and am looking into lazy-validation of parameters.  In other words, `py.test` will only validate `--ansible-*` parameters if you are using the `pytest-ansible` fixtures in your test.

**Comment by jlaska** [comment]
`pytest-ansible-1.2.5` has been released which should address the reported issue.  Please feel free to retest, and let me know if the problem remains.  Thanks!

**Comment by lokesh8421** [comment]
with latest pytest-anisble, getting the same error>
root@]#  pytest -s  test_ping.py
==================================================== test session starts =====================================================
platform linux -- Python 3.6.8, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
ansible: 2.9.27
rootdir: /root/lkambadu/tcpip
plugins: ansible-2.2.4
collected 1 item

=================================================== no tests ran in 0.03s ====================================================
ERROR: Missing required parameter --ansible-host-pattern/--host-pattern

[root@]#
