### ISSUE TITLE
How do to run different commands on indvidual hosts matching pattern all

### ISSUE THREAD

**Issue by mrniranjan** [jlaska/pytest-ansible#5]
i would like to know how i can run different commands on individual hosts matching pattern all

```
Example:
Inventory File
[server]
192.168.122.12

[client]
192.168.122.13
```

```

@pytest.mark.ansible(host_pattern='all')
def test_1(ansible_module):
     <individual_host1/server>.ansible_module.command ('hostname')
    <individual_host2/client>.ansible_module.command('date')
```

I am aware i could do the below:

```
@pytest.mark.ansible(host_pattern='server')
output = ansible_module.command('hostname')

@pytest.mark.ansible(host_pattern='client')
output = ansible_module.command('date')
```

But i have a requirement where i need certain tests 
where i need to match pattern "all" but inside the tests i need to run individual commands on
each host.

**Comment by mrniranjan** [comment]
Any update on this ?

**Comment by jlaska** [comment]
Greetings @mrniranjan , thanks for the issue.

You could certainly make this work with the current code base, but it's not a supported scenario presently.  Basically, you'd want to reinitialize the `AnsibleModule` within your test (e.g. https://github.com/jlaska/pytest-ansible/blob/master/pytest_ansible/plugin.py#L531-L537).  Again, unsupported with the current code base, so you may have more luck rethinking/restructuring your tests.

**Comment by mrniranjan** [comment]
Any update on this ?

**Comment by jlaska** [comment]
@mrniranjan Greetings!  The code is complete, and undergoing testing.  If you'd like to experiment, please see the https://github.com/jlaska/pytest-ansible/tree/host_manager branch

**Comment by mrniranjan** [comment]
Yes definitely, Thanks for letting us know.

**Comment by mrniranjan** [comment]
Do you have any example ?, like running individual commands like 'date/hostname' on individual systems with hosts pattern matching 'all'.

**Comment by jlaska** [comment]
@mrniranjan Checkout the `README.md` in that branch for some basic examples.  More will be needed in the docs, specifically around handling the response objects.

```python
results = ansible_adhoc().all.command('date')
for result in results.items():
    assert result.is_successful  # e.g. not is_failed
# The AdHocResult class supports `getitem` and `getattr` and 
# offers an iterator to access results-per host.  A specific host result
# returned in the ModuleResult class.  This class is a `dict` wrapper 
# around the ansible module JSON response and offers convenience 
# properties (e.g. `is_ok`, `is_changed`, `is_failed`).
```

If no parameters are supplied to `ansible_adhoc()`, the command-line `py.test` parameters are assumed.  Otherwise, override as needed ...

```python
result = ansible_adhoc(inventory='localhost,', connection='local').localhost.ping()
assert result.localhost.is_ok
```

**Comment by mrniranjan** [comment]
I have a below inventory file

```
[client]
192.168.122.244 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa

[server]
192.168.122.60 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa
```

Now i want to match pattern all (i.e both server and client) in a function, but inside my test function, i would like to run different commands on client and server. 

```
@pytest.mark.ansible(host_pattern='all')
def test4(ansible_adhoc):
      client_host = ansible_adhoc(host_pattern='client')
      client_host.command('hostname')

      server_host = ansible_adhoc(host_pattern='server')
      server_host.command('date')
```
i would like to do something like above.

**Comment by jlaska** [comment]
@mrniranjan you shouldn't need to break out `client_host` and `server_host`.  Just let `ansible_adhoc` do the split for you.

```python
client_results = ansible_adhoc().client.command('hostname')
server_date = ansible_adhoc().server.command('date')
```

The use of `ansibl_adhoc` largely obviates the need for the `pytest.mark.ansible` property.

**Comment by mrniranjan** [comment]
@jlaska it works with files starting with test_* but doesn't seem to work on conftest.py 

Below is my code in conftest.py

```
import pytest

@pytest.fixture
def mysetup(ansible_adhoc):
    output = ansible_adhoc.windows.win_command('whoami')
    return output
```
Below is test2.py

```
def test1(mysetup):
    print(mysetup)

def test2():
    pass

def test3():
    pass
```
Below is the command used:
py.test --ansible-inventory=inventory.txt --ansible-host-pattern=all test2.py  -s -v

Output:
```
platform linux2 -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/mniranja/python_proj/bin/python
cachedir: .cache
ansible: 2.2.1.0
rootdir: /home/mniranja/source/ansible/pytest_ansible, inifile: 
plugins: multihost-1.1, ansible-2.0.0, modifyjunit-1.0
collected 3 items 

test2.py::test1 ERROR
test2.py::test2 PASSED
test2.py::test3 PASSED
___ ERROR at setup of test1 ___
ansible_adhoc = <function init_host_mgr at 0x7f6332971d70>

    @pytest.fixture
    def mysetup(ansible_adhoc):
>       output = ansible_adhoc.windows.win_command('whoami')
E       AttributeError: 'function' object has no attribute 'windows'

conftest.py:5: AttributeError

```

My inventory file looks like below:

```
[client]
192.168.122.244 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa

[server]
192.168.122.60 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa

[windows]
192.168.122.187

[windows:vars]
ansible_user = administrator
ansible_password = Secret123
ansible_port = 5985
ansible_connection = winrm
ansible_winrm_server_cert_validation = ignore
ansible_winrm_scheme = http
ansible_winrm_transport=ntlm
```

Any ideas as to why it doesn't work when ansible_adhoc is used in conftest.py

**Comment by jlaska** [comment]
> >       output = ansible_adhoc.windows.win_command('whoami')
> E       AttributeError: 'function' object has no attribute 'windows'

Notice the traceback.  `ansible_adhoc` is a generator function and must be called as a function.

Try ...

```python
output = ansible_adhoc().windows.win_command('whoami')
```

**Comment by mrniranjan** [comment]
Sorry my bad, failed to notice that.

**Comment by jlaska** [comment]
> Sorry my bad, failed to notice that.

All good, thanks for experimenting this this branch :)

**Comment by mrniranjan** [comment]
I am still testing, I would like add another requirement of my usecase i.e sometimes we have inventories as below:

```
[master]
192.168.122.244 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa
192.168.122.233 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa

[clone]
192.168.122.60 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa
192.168.122.65 ansible_connection=ssh ansible_ssh_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa
```
When we have multiple machines under ''master'' , we have requirement where in a test case the each machine under server has different commands to be executed. 

For example when we have 2 machines under master, we need to setup an ldap server on master1 (192.168.122.244) and setup a different ldap server instance on master2 (192.168.122.233). I.e we need to execute different commands in a single test case on different machines under master and same with clients. 

Right now we use a pytest plugin called multihost (https://pypi.python.org/pypi/pytest-multihost) to achieve this.  when multiple hosts are available under a role/tag (master), it's considered as list so we get master[0], master[1]. and we could execute commands as master[0].run_command, master[1].run_command. 

Could the same be available using ansible_adhoc ? like ansible_adhoc().windows[0].

**Comment by jlaska** [comment]
@mrniranjan with `ansible_adhoc()`, any host pattern (http://docs.ansible.com/ansible/intro_patterns.html) you can specify in ansible, you can use that in pytest-ansible.

```python
results = ansible_adhoc()['master[0]'].command('do_things')
results = ansible_adhoc()['master[1]'].command('do_other_things')
```

**Comment by mrniranjan** [comment]
it looks like ansible_module, ansible_adhoc are by default function scoped fixtures, would it be possible to not limit to specific scope . In our tests, we would like to define functions as fixtures which use ansible_adhoc, ansible_module and these functions can be scoped as session, module etc. 

Example:
```
@pytest.fixture(scope="session")
def update_resolv_conf(request, ansible_adhoc, ansible_module):
    inventory = ansible_module.options['inventory_manager'].get_group_dict()
    windows_ip = inventory['windows']
    ansible_adhoc().atomic.command('cp /etc/resolv.conf ',
                                   '/etc/resolv.conf.backup')
    ansible_adhoc().atomic.linefile(dest='/etc/resolv.conf',
                                    regexp='^search',
                                    insertbefore='^nameserver',
                                    line='nameserver %s' % (str(windows_ip[0])))

    def restore_resolv_conf():
        ansible_adhoc().atomic.command('cp /etc/resolv.conf.backup ',
                                       '/etc/resolv.conf')
    request.addfinalizer(restore_resolv_conf)

```

**Comment by jlaska** [comment]
There are no plans for session-scoped fixtures at this time.  I've always had trouble mixing fixture scopes, if someone has suggestions (PRs) for doing that right, I'd gladly review!

**Comment by mrniranjan** [comment]
Would it be possible to merge this with master , In our limited testing that i have done,it works as expected barring the feature of limiting the scope to "function", Would it be possible to merge this with master and also package in fedora ( i can help if needed) , that way we can have more adoption.

**Comment by jlaska** [comment]
@mrniranjan merging the PR shortly.  I'll be looking into changes to the scope of the `ansible_adhoc` fixture next.
